name: Build Replicad Studio

on: 
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Clone Replicad Latest
        run: |
          git clone https://github.com/sgenoud/replicad.git temp
          ls temp/

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: temp/pnpm-lock.yaml

      - name: Install and Build
        working-directory: temp
        run: |
          pnpm install
          pnpm run build --filter=studio
          ls -lh packages/studio/dist/

      - name: Upload Studio Files
        uses: actions/upload-artifact@v4
        with:
          name: replicad-studio-dist
          path: temp/packages/studio/dist/
